#!/usr/bin/env bash

set -e

# create -n 1 /foo/
# create -n 2 /foo/bar/
# create -n 3 /{path}/
# create -n 4 /{path}/{id}/
# create -n 5 /{path}/bar
# create -n 6 /foo /foo/
# create -n 7 /foo/ /foo
# create -n 8 /foo/ /foo/bar
# create -n 9 /foo/ /foo/bar/
# create -n 10 /foo /{path}
# create -n 11 /foo /{path}/
# create -n 12 /foo/ /{path}
# create -n 13 /foo/ /{path}/
# create -n 14 /{path} /{path}/
# create -n 15 /{path}/ /{path}
# create -n 16 /{path} /{path}/{id}
# create -n 17 /{path}/ /{path}/{id}
# create -n 18 /foo/bar/ /foo/{id}

# run -m main -l csharp
# run -m main -l go
# run -m main -l java
# run -m main -l php
# run -m main -l python
# run -m main -l typescript

# read -p "Update results/ then continue"

prep -n -t ascii \
    -l csharp \
    -l go \
    -l java \
    -l php \
    -l python \
    -l typescript \
    -e -d report_header.md -b kiota-results-table -o README.md
prep -n -t ascii \
    -l csharp \
    -l go \
    -l java \
    -l php \
    -l python \
    -l typescript \
    -e -i -b kiota-results-table -o report_main_highlights.md
prep -n -t ascii -l csharp     -e -o report_main_csharp.md
prep -n -t ascii -l go         -e -o report_main_go.md
prep -n -t ascii -l java       -e -o report_main_java.md
prep -n -t ascii -l php        -e -o report_main_php.md
prep -n -t ascii -l python     -e -o report_main_python.md
prep -n -t ascii -l typescript -e -o report_main_typescript.md
